#define INCORRECT_KEYWORD "неверное ключевое слово"
#define INCORRECT_RELATION "неверное отношение"
#define INCORRECT_CONSTANT "неверная запись константы"
#define INCORRECT_SYMBOL "неизвестный символ"
#define LABEL_BEGIN "строка не начинается с метки"
#define KEYWORD_AFTER_LABEL "оператор не начинается с ключевого слова"
#define VAR_EXPECTED "отсутствует переменная после ключевого слова"
#define LABEL_EXPECTED "отсутствует метка после ключевого слова"
#define NO_ASSINGMENT "отсутствует = после переменной"